In [1]:
import pandas as pd
df = pd.read_csv('./../Datasets/data.csv')

In [2]:
df.head()

,Sr.No,Institute Code,Institute Name,CS-CAP1,Location
0,1,3012,Veermata Jijabai Technological Institute(VJTI)...,37.00,Dadar
1,2,3014,"Sardar Patel College of Engineering, Andheri",0.00,Andheri
2,3,3135,Manjara Charitable Trust's Rajiv Gandhi Instit...,3.33,Andheri
3,4,3139,"Vidyalankar Institute of Technology,Wadala, Mu...",13.67,Dadar
4,5,3146,Jawahar Education Society's Annasaheb Chudaman...,3.00,Vashi

In [3]:
df.shape

(23, 5)

In [4]:
df.Location.unique()

array(['Dadar', 'Andheri', 'Vashi', 'Borivali', 'Bandra'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
locs = le.fit_transform(df[['Location']])

c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [7]:
df['Encoded_Location'] = locs

In [8]:
df

,Sr.No,Institute Code,Institute Name,CS-CAP1,Location,Encoded_Location
0,1,3012,Veermata Jijabai Technological Institute(VJTI)...,37.00,Dadar,3
1,2,3014,"Sardar Patel College of Engineering, Andheri",0.00,Andheri,0
2,3,3135,Manjara Charitable Trust's Rajiv Gandhi Instit...,3.33,Andheri,0
3,4,3139,"Vidyalankar Institute of Technology,Wadala, Mu...",13.67,Dadar,3
4,5,3146,Jawahar Education Society's Annasaheb Chudaman...,3.00,Vashi,4
5,6,3148,Mahavir Education Trust's Shah & Anchor Kutchh...,1.67,Dadar,3
6,7,3154,Saraswati Education Society's Saraswati Colleg...,0.00,Vashi,4
7,8,3174,"Ramrao Adik Edu Soc, Ramarao Adik Institute of...",5.33,Vashi,4
8,9,3175,M.G.M.'s College of Engineering and Technology...,1.67,Vashi,4
9,10,3176,"Thakur College of Engineering and Technology, ...",7.67,Borivali,2
10,11,3181,"K.J.Somaiya College of Engineering, Vidyavihar...",19.00,Dadar,3
11,12,3184,Fr. Conceicao Rodrigues College of Engineering...,0.00,Bandra,1
12,13,3185,Vivekanand Education Society's Institute of Te...,1.00,Vashi,4
13,14,3187,"N.Y.S.S.'s Datta Meghe College of Engineering,...",1.67,Vashi,4
14,15,3189,"Bharati Vidyapeeth College of Engineering, Nav...",4.00,Vashi,4
15,16,3190,"Terna Engineering College, Nerul, Navi Mumbai",9.67,Vashi,4
16,17,3196,"Lokmanya Tilak College of Engineering, Kopar K...",3.67,Vashi,4
17,18,3197,Agnel Charities' FR. C. Rodrigues Institute of...,0.00,Vashi,4
18,19,3199,Shri Vile Parle Kelvani Mandal's Dwarkadas J. ...,16.33,Andheri,0
19,20,3204,"St. Francis Institute of Technology,Borivali, ...",9.00,Borivali,2
20,21,3207,Mahatma Education Society's Pillai College of ...,1.67,Vashi,4
21,22,3215,Bhartiya Vidya Bhavan's Sardar Patel Institute...,29.00,Andheri,0
22,23,3423,"Shree L.R. Tiwari College of Engineering, Mira...",5.00,Borivali,2

In [9]:
df[['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Vashi']] = pd.get_dummies(df.Encoded_Location)

In [10]:
df

,Sr.No,Institute Code,Institute Name,CS-CAP1,Location,Encoded_Location,Andheri,Bandra,Borivali,Dadar,Vashi
0,1,3012,Veermata Jijabai Technological Institute(VJTI)...,37.00,Dadar,3,0,0,0,1,0
1,2,3014,"Sardar Patel College of Engineering, Andheri",0.00,Andheri,0,1,0,0,0,0
2,3,3135,Manjara Charitable Trust's Rajiv Gandhi Instit...,3.33,Andheri,0,1,0,0,0,0
3,4,3139,"Vidyalankar Institute of Technology,Wadala, Mu...",13.67,Dadar,3,0,0,0,1,0
4,5,3146,Jawahar Education Society's Annasaheb Chudaman...,3.00,Vashi,4,0,0,0,0,1
5,6,3148,Mahavir Education Trust's Shah & Anchor Kutchh...,1.67,Dadar,3,0,0,0,1,0
6,7,3154,Saraswati Education Society's Saraswati Colleg...,0.00,Vashi,4,0,0,0,0,1
7,8,3174,"Ramrao Adik Edu Soc, Ramarao Adik Institute of...",5.33,Vashi,4,0,0,0,0,1
8,9,3175,M.G.M.'s College of Engineering and Technology...,1.67,Vashi,4,0,0,0,0,1
9,10,3176,"Thakur College of Engineering and Technology, ...",7.67,Borivali,2,0,0,1,0,0
10,11,3181,"K.J.Somaiya College of Engineering, Vidyavihar...",19.00,Dadar,3,0,0,0,1,0
11,12,3184,Fr. Conceicao Rodrigues College of Engineering...,0.00,Bandra,1,0,1,0,0,0
12,13,3185,Vivekanand Education Society's Institute of Te...,1.00,Vashi,4,0,0,0,0,1
13,14,3187,"N.Y.S.S.'s Datta Meghe College of Engineering,...",1.67,Vashi,4,0,0,0,0,1
14,15,3189,"Bharati Vidyapeeth College of Engineering, Nav...",4.00,Vashi,4,0,0,0,0,1
15,16,3190,"Terna Engineering College, Nerul, Navi Mumbai",9.67,Vashi,4,0,0,0,0,1
16,17,3196,"Lokmanya Tilak College of Engineering, Kopar K...",3.67,Vashi,4,0,0,0,0,1
17,18,3197,Agnel Charities' FR. C. Rodrigues Institute of...,0.00,Vashi,4,0,0,0,0,1
18,19,3199,Shri Vile Parle Kelvani Mandal's Dwarkadas J. ...,16.33,Andheri,0,1,0,0,0,0
19,20,3204,"St. Francis Institute of Technology,Borivali, ...",9.00,Borivali,2,0,0,1,0,0
20,21,3207,Mahatma Education Society's Pillai College of ...,1.67,Vashi,4,0,0,0,0,1
21,22,3215,Bhartiya Vidya Bhavan's Sardar Patel Institute...,29.00,Andheri,0,1,0,0,0,0
22,23,3423,"Shree L.R. Tiwari College of Engineering, Mira...",5.00,Borivali,2,0,0,1,0,0

In [11]:
df.rename(columns={'CS-CAP1':'Marks'}, inplace=True)

In [12]:
df

,Sr.No,Institute Code,Institute Name,Marks,Location,Encoded_Location,Andheri,Bandra,Borivali,Dadar,Vashi
0,1,3012,Veermata Jijabai Technological Institute(VJTI)...,37.00,Dadar,3,0,0,0,1,0
1,2,3014,"Sardar Patel College of Engineering, Andheri",0.00,Andheri,0,1,0,0,0,0
2,3,3135,Manjara Charitable Trust's Rajiv Gandhi Instit...,3.33,Andheri,0,1,0,0,0,0
3,4,3139,"Vidyalankar Institute of Technology,Wadala, Mu...",13.67,Dadar,3,0,0,0,1,0
4,5,3146,Jawahar Education Society's Annasaheb Chudaman...,3.00,Vashi,4,0,0,0,0,1
5,6,3148,Mahavir Education Trust's Shah & Anchor Kutchh...,1.67,Dadar,3,0,0,0,1,0
6,7,3154,Saraswati Education Society's Saraswati Colleg...,0.00,Vashi,4,0,0,0,0,1
7,8,3174,"Ramrao Adik Edu Soc, Ramarao Adik Institute of...",5.33,Vashi,4,0,0,0,0,1
8,9,3175,M.G.M.'s College of Engineering and Technology...,1.67,Vashi,4,0,0,0,0,1
9,10,3176,"Thakur College of Engineering and Technology, ...",7.67,Borivali,2,0,0,1,0,0
10,11,3181,"K.J.Somaiya College of Engineering, Vidyavihar...",19.00,Dadar,3,0,0,0,1,0
11,12,3184,Fr. Conceicao Rodrigues College of Engineering...,0.00,Bandra,1,0,1,0,0,0
12,13,3185,Vivekanand Education Society's Institute of Te...,1.00,Vashi,4,0,0,0,0,1
13,14,3187,"N.Y.S.S.'s Datta Meghe College of Engineering,...",1.67,Vashi,4,0,0,0,0,1
14,15,3189,"Bharati Vidyapeeth College of Engineering, Nav...",4.00,Vashi,4,0,0,0,0,1
15,16,3190,"Terna Engineering College, Nerul, Navi Mumbai",9.67,Vashi,4,0,0,0,0,1
16,17,3196,"Lokmanya Tilak College of Engineering, Kopar K...",3.67,Vashi,4,0,0,0,0,1
17,18,3197,Agnel Charities' FR. C. Rodrigues Institute of...,0.00,Vashi,4,0,0,0,0,1
18,19,3199,Shri Vile Parle Kelvani Mandal's Dwarkadas J. ...,16.33,Andheri,0,1,0,0,0,0
19,20,3204,"St. Francis Institute of Technology,Borivali, ...",9.00,Borivali,2,0,0,1,0,0
20,21,3207,Mahatma Education Society's Pillai College of ...,1.67,Vashi,4,0,0,0,0,1
21,22,3215,Bhartiya Vidya Bhavan's Sardar Patel Institute...,29.00,Andheri,0,1,0,0,0,0
22,23,3423,"Shree L.R. Tiwari College of Engineering, Mira...",5.00,Borivali,2,0,0,1,0,0

In [13]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [14]:
X_data = df[['Marks', 'Andheri', 'Bandra', 'Borivali', 'Dadar', 'Vashi']]
y_data = df['Institute Name']

In [15]:
model.fit(X_data, y_data)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [16]:
model.score(X_data, y_data)

0.8695652173913043

In [17]:
model.predict([[23,0,0,0,1,0]])

array(['K.J.Somaiya College of Engineering, Vidyavihar, Mumbai'],
      dtype=object)

In [18]:
from joblib import dump

In [19]:
dump(model, './../Models/masters.joblib')

['./../Models/masters.joblib']

In [20]:
model.predict([[12,0,0,0,1,0]])

array(['Vidyalankar Institute of Technology,Wadala, Mumbai'], dtype=object)